DROP DATABASE IF EXISTS trail;

CREATE DATABASE trail;

USE trail;

DROP TABLE IF EXISTS testing;

CREATE TABLE testing (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	password MEDIUMTEXT NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)	
)