DROP DATABASE IF EXISTS trail;

CREATE DATABASE trail;

USE trail;

DROP TABLE IF EXISTS testing;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS publicPosts;

CREATE TABLE testing (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	password MEDIUMTEXT NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE user (
  id INTEGER NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password TEXT NOT NULL,
  email VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE posts (
  id INTEGER NOT NULL AUTO_INCREMENT,
  userID INTEGER,
  recipientUserID INTEGER,
  longitude TEXT NOT NULL,
  latitude TEXT NOT NULL,
  imageURL VARCHAR(255) NOT NULL,
  public BOOLEAN NOT NULL,
  timePosted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  timeExpired TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- ---
-- Foreign Keys Undefined
-- ---
ALTER TABLE posts ADD FOREIGN KEY (userID) REFERENCES user (id);
